### ISSUE TITLE
Find a better solution to Node.js bot

### ISSUE THREAD

**Issue by dminca** [WizDevOps/automator-bot#8]
The current version is being built with _yeoman_ which is going to be hard to automate, unless you are willing to create custom commands for the _yeoman generator_ ...

## TODO
- [x] find a better solution to **mark down** the objective: **create event-driven slack bot**
- [x] preferred language: Python 3+
- [x] check out [python-rtmbot](https://github.com/slackhq/python-rtmbot/)
- [x] another resource to check out [python-slackclient](https://github.com/slackhq/python-slackclient)

## References
* [How to write a slack bot @ medium.com](https://medium.com/@julianmartinez/how-to-write-a-slack-bot-end-to-end-d6a8542c854b#.e6ard75fr)
* [Slack Platform @ API Slack Python](https://api.slack.com/community#python)
* [slacker](https://github.com/os/slacker)
